services:
  - type: web
    name: queen-ruva ai beta
    env: node
    plan: free  
    region: singapore  
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /  
    autoDeploy: false  
